spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/Kamperk/Microservices/configs.git
          search-paths: /

server:
  port: 8071

management:
  trace:
    enabled: true
  context-path: /
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"


